# 7 Data Cleaning and Preparation

## 7.1 Handling missing data

### 7.1.1 Filtering out missing data

In [2]:
import pandas as pd
import numpy as np
from numpy import nan as NA
data = pd.Series([1,NA,3.5,NA,7])

In [6]:
#first way to filter missing data in Series
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
#second way to filter missing data in Series
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [19]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])
data[4]=NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
#filter missing data in DataFrame
#1）row
data.dropna(how='all')

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [15]:
#2）column
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
#3）keep rows with certain number
data.dropna(thresh=2)

0    1    2   4
0  1.0  6.5  3.0 NaN
3  NaN  6.5  3.0 NaN

### 7.1.2 Filling in missing data

In [35]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4,1] = NA
df.iloc[:2,2] = NA
df

0         1         2
0 -0.851737       NaN       NaN
1  0.257080       NaN       NaN
2 -0.168585       NaN -0.591165
3  1.568839       NaN -0.801112
4  1.312338  1.629649 -1.849256
5  0.964850  0.972250 -0.422392
6  0.105211 -0.839859 -0.853587

In [36]:
# fill value for column with a dict
df.fillna({1: 0.5,2:0})

0         1         2
0 -0.851737  0.500000  0.000000
1  0.257080  0.500000  0.000000
2 -0.168585  0.500000 -0.591165
3  1.568839  0.500000 -0.801112
4  1.312338  1.629649 -1.849256
5  0.964850  0.972250 -0.422392
6  0.105211 -0.839859 -0.853587

In [41]:
#interpolation method upward with limit
df.fillna(method='bfill',limit=2)

0         1         2
0 -0.851737       NaN -0.591165
1  0.257080       NaN -0.591165
2 -0.168585  1.629649 -0.591165
3  1.568839  1.629649 -0.801112
4  1.312338  1.629649 -1.849256
5  0.964850  0.972250 -0.422392
6  0.105211 -0.839859 -0.853587

## 7.2 Data transformation

### 7.2.1 Removing duplicates

In [42]:
data = pd.DataFrame({'k1':['one','two']*3+['two'],
                     'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [43]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [46]:
data['v1']=range(7)

In [47]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [48]:
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### ***7.2.2 Transforming data using a function or mapping

In [49]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon',
                            'Pastrami','corned beef','Bacon',
                            'pastrami','honey ham','nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [53]:
#map each distinct meat type to animals
meat_to_animal={
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [54]:
#covert food value to lowercase
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [59]:
#map animal to food
data['animal']=lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [58]:
# pass a function to map
data['food'].map(lambda x:meat_to_animal[x.lower()])
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

### 7.2.3 Replacing values

In [60]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [61]:
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [62]:
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 7.2.4 Renaming axis indexes

In [63]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                   index=['Ohio','Colorado','New York'],
                   columns=['one','two','three','four'])

# Remain Question

In [64]:
# use map method to rename the index
transform = lambda x:x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [68]:
# use rename method to rename the index
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [72]:
# use rename method to rename the index with dict-like object
data.rename(index={'Ohio':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

### 7.2.5 Discretization and binning

In [78]:
# divide data into bins
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [80]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [79]:
data = np.random.rand(20)
data

array([0.63928152, 0.49393649, 0.22230527, 0.12489356, 0.77048616,
       0.18078465, 0.15812264, 0.63892715, 0.95155636, 0.82180814,
       0.72370195, 0.68713649, 0.39000188, 0.23319721, 0.46253702,
       0.55930647, 0.61431805, 0.69759856, 0.54222228, 0.97102961])

In [82]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [83]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [84]:
pd.cut(ages,[18,26,36,61,100],right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [85]:
group_names = ['Youth','YoungAdult','MiddleAged','Senior']
pd.cut(ages,bins,labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [86]:
# compute equal-length bins
data = np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.11, 0.32], (0.11, 0.32], (0.54, 0.75], (0.54, 0.75], (0.11, 0.32], ..., (0.32, 0.54], (0.32, 0.54], (0.11, 0.32], (0.32, 0.54], (0.11, 0.32]]
Length: 20
Categories (4, interval[float64]): [(0.11, 0.32] < (0.32, 0.54] < (0.54, 0.75] < (0.75, 0.96]]

In [87]:
# compute roughly equal-size bins
data = np.random.randn(1000)
cats = pd.qcut(data,4)
cats

[(-0.694, -0.0387], (-2.71, -0.694], (-2.71, -0.694], (0.627, 3.654], (-0.694, -0.0387], ..., (0.627, 3.654], (-0.694, -0.0387], (-2.71, -0.694], (-2.71, -0.694], (-0.0387, 0.627]]
Length: 1000
Categories (4, interval[float64]): [(-2.71, -0.694] < (-0.694, -0.0387] < (-0.0387, 0.627] < (0.627, 3.654]]

In [88]:
pd.value_counts(cats)

(0.627, 3.654]       250
(-0.0387, 0.627]     250
(-0.694, -0.0387]    250
(-2.71, -0.694]      250
dtype: int64

In [89]:
pd.qcut(data,[0,0.1,0.5,0.9,1])

[(-1.357, -0.0387], (-2.71, -1.357], (-2.71, -1.357], (-0.0387, 1.235], (-1.357, -0.0387], ..., (-0.0387, 1.235], (-1.357, -0.0387], (-2.71, -1.357], (-2.71, -1.357], (-0.0387, 1.235]]
Length: 1000
Categories (4, interval[float64]): [(-2.71, -1.357] < (-1.357, -0.0387] < (-0.0387, 1.235] < (1.235, 3.654]]

### 7.2.6 Detecting and filtering outliers

In [90]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.018775    -0.001830     0.020268    -0.002136
std       0.993021     0.997412     0.956969     1.020161
min      -3.519082    -3.052413    -3.551218    -3.239511
25%      -0.648567    -0.695435    -0.638667    -0.693565
50%       0.033344     0.031812     0.028403     0.009893
75%       0.656203     0.663867     0.634936     0.678387
max       2.796271     2.968145     2.788447     4.100095

In [91]:
# find values in one of the columns exceeding 3
col = data[2]
col[np.abs(col)>3]

117   -3.551218
790   -3.145070
Name: 2, dtype: float64

# Remain Question

In [96]:
# find all rows having a value exceeding 3 or -3
data[(np.abs(data)>3).any(1)]

0         1         2         3
117 -0.732972 -0.628581 -3.551218 -1.764388
260 -0.300259 -0.173846  0.726521  4.100095
428 -0.298007  0.159379  0.466471  3.371742
488 -0.011597 -0.388780 -0.344684 -3.239511
642 -3.519082 -2.087579  1.497457  0.190858
790  0.656043 -0.271797 -3.145070 -1.999072
824  1.653132 -0.821856  0.031386  3.049399
849  0.043734  0.531417 -0.396478 -3.033364
891  0.974895 -3.052413  0.395767  0.204676

# Remain Question

In [97]:
# cap values outside the interval -3 to 3
data[np.abs(data)>3]=np.sign(data)*3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.019294    -0.001777     0.020964    -0.003385
std       0.991304     0.997253     0.954596     1.014167
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.648567    -0.695435    -0.638667    -0.693565
50%       0.033344     0.031812     0.028403     0.009893
75%       0.656203     0.663867     0.634936     0.678387
max       2.796271     2.968145     2.788447     3.000000

In [98]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0  1.0
1 -1.0 -1.0 -1.0 -1.0
2  1.0 -1.0  1.0 -1.0
3 -1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

### 7.2.7 Permutation and random sampling

In [4]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [5]:
sampler = np.random.permutation(5)
sampler

array([0, 3, 4, 1, 2])

In [6]:
df.take(sampler)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11

In [7]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
0   0   1   2   3
3  12  13  14  15

# Remain Question

In [8]:
choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True)
draws

4    4
0    5
4    4
4    4
1    7
3    6
3    6
1    7
0    5
4    4
dtype: int64

### 7.2.8 Computing indicator/dummy variables

# Remain Question

In [9]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'data1':range(6)})
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [10]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [12]:
mnames = ['movie_id','title','genres']
movies = pd.read_table('../datasets/movielens/movies.dat',sep='::',
                      header=None, names=mnames)
movies[:10]

E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [13]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [15]:
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [16]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [17]:
for i,gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1

In [18]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [22]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [23]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 String manipulation

### 7.3.1 String object methods

In [29]:
# take apart and trim whitespace of strings
val = 'a,b, guido'
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [36]:
# join strings together
'::'.join(pieces)

'a::b::guido'

In [37]:
# detect a substring
# 1)"in" keyword
'guido' in val

True

In [39]:
# 2)index method
val.index('b')

2

In [43]:
# 3)find method
val.find('9')

-1

### 7.3.2 Regular expressions

In [46]:
# split a string with a variable number of whitespace
import re
text = "foo     bar\t baz    \tqux"
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [49]:
# split a string with a variable number of whitespace by self compile 
#(saving CPU when apply to many strings)
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [48]:
# get the list of all patterns matching the regex
regex.findall(text)

['     ', '\t ', '    \t']

In [61]:
# use the regular expression to identify email address
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

regex = re.compile(pattern,flags=re.IGNORECASE)

# return a list of tuples
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [59]:
# return a tuple of the pattern components with groups method
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [62]:
# group substrings
print(regex.sub(r'Username:\1,Domain:\2,Suffix:\3',text))

Dave Username:dave,Domain:google,Suffix:com
Steve Username:steve,Domain:gmail,Suffix:com
Rob Username:rob,Domain:gmail,Suffix:com
Ryan Username:ryan,Domain:yahoo,Suffix:com


### 7.3.3 Vectorized string functions in pandas

In [63]:
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com',
       'Rob':'rob@gmail.com','Wes':np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [64]:
# check whether each email address has 'gmail' with sty.contain
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [65]:
# check whether each email address has 'gmail' with regular expression
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [66]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [71]:
# access elements in the embedded lists with .str.get()
data.str.get(4)

Dave       @
Steve      e
Rob        g
Wes      NaN
dtype: object

In [75]:
# access elements in the embedded lists with .str[]
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object