In [133]:
# 1导入numpy库并简写为 np
import numpy as np

In [135]:
# 2.打印numpy的版本和配置说明
print(np.__version__,np.show_config)

1.15.4 <function show at 0x000001CDDC53A510>


In [29]:
# 3.创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
# 4.如何找到任何一个数组的内存大小？
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [46]:
# 5.如何从命令行得到numpy中add函数的说明文档?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [31]:
# 6.创建一个长度为10并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
# 7.创建一个值域范围从10到49的向量
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
# 8.反转一个向量(第一个元素变为最后一个)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [34]:
# 9.创建一个 3x3 并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# 10.找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [36]:
# 11.创建一个 3x3 的单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
# 12. 创建一个 3x3x3的随机数组
Z = np.random.random((3,3,3))
print(Z)

[[[0.07550579 0.52581294 0.68802496]
  [0.96634381 0.59929977 0.45221967]
  [0.48063538 0.60627731 0.28663324]]

 [[0.24909215 0.39706963 0.18228038]
  [0.22416956 0.00325136 0.85796467]
  [0.75928213 0.09285065 0.46560094]]

 [[0.28191494 0.04412588 0.44913972]
  [0.2106296  0.54088472 0.90947333]
  [0.87481685 0.80313023 0.31766441]]]


In [38]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 
Z = np.random.random((10,10))
print(Z)
print(Z.max(),Z.min())

[[0.91594083 0.42664164 0.16464361 0.84521999 0.62128921 0.36579389
  0.67197404 0.38807573 0.56528271 0.16594682]
 [0.96367788 0.21930991 0.03823384 0.75016834 0.05454083 0.60381557
  0.76651785 0.69467938 0.53143947 0.33660363]
 [0.46089037 0.6783934  0.94419171 0.20760785 0.26471304 0.67080953
  0.69612618 0.64239647 0.64690949 0.41350905]
 [0.16567988 0.36910476 0.51952003 0.66774108 0.29463307 0.44813574
  0.32811589 0.77479151 0.2672339  0.92281454]
 [0.57293209 0.2188253  0.18211464 0.71715385 0.44229924 0.51672852
  0.62578023 0.28769819 0.95647263 0.55387183]
 [0.3951306  0.44558387 0.24908458 0.36733401 0.36565902 0.28770623
  0.14576306 0.66754296 0.76574144 0.11746592]
 [0.70859471 0.829364   0.75229066 0.22302941 0.98027996 0.92691859
  0.5976727  0.90299428 0.070595   0.4703711 ]
 [0.4901716  0.62831265 0.22224908 0.78191546 0.69324389 0.62876314
  0.66098271 0.69499037 0.29050535 0.94444801]
 [0.49516263 0.04425588 0.78052904 0.46895419 0.07670263 0.16645736
  0.91699719

In [39]:
# 14. 创建一个长度为30的随机向量并找到它的平均值 
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.20725082 0.08361989 0.67253836 0.00971226 0.96599237 0.43722164
 0.57391069 0.69051281 0.07990792 0.16137404 0.46867362 0.46992561
 0.99223798 0.35633413 0.17699172 0.38909015 0.5579309  0.05384233
 0.27262055 0.9436634  0.28658017 0.73170397 0.80113884 0.07379651
 0.81363448 0.2288429  0.71980144 0.48829049 0.12854559 0.45586777]
0.44305177793006406


In [40]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
# 16. 对于一个存在在数组，如何添加一个用0填充的边界? 
Z = np.ones((5,5))
Z = np.pad(Z,pad_width = 1, mode = 'constant',constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
# 17. 以下表达式运行的结果分别是什么?
0 * np.nan
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

False
False
nan
False


In [49]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
Z = np.diag(1 + np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [54]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式 array[beg:end:step]
# 对于多维数组 x[1,2] 表示第1行，第2列
Z = np.zeros((8,8),dtype = int)
Z[1::2, ::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [68]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [69]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
# 22. 对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(),Z.min()
Z = (Z - Zmin)/(Zmax-Zmin)
print(Z)

[[0.73344878 0.40003946 0.48966686 0.7978798  0.50880422]
 [1.         0.64335108 0.82774182 0.22077019 0.51501335]
 [0.33695842 0.21739072 0.86051665 0.09673378 0.46895669]
 [0.11010024 0.70436502 0.77364328 0.27673266 0.        ]
 [0.7157376  0.10792081 0.99613199 0.47162704 0.87182487]]


In [74]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype
color = np.dtype([("r", np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [77]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [83]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反
Z = np.arange(11)
Z[(3<Z) & (Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [100]:
# 26. 下面脚本运行后的结果是什么?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [98]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个? 
Z = np.arange(5)
Z ** Z

2 << Z >> 2

Z < -Z

1j*Z

Z/1/1

Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [104]:
# 28. 下列表达式的结果分别是什么?
print(np.array(0)/np.array(0))

print(np.array(0) // np.array(0))

np.array([np.nan]).astype(int).astype(float)

nan
0


E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


array([-2.14748365e+09])

In [105]:
# 29. 如何从零位对浮点数组做舍入 ?
Z =np.random.uniform(-10, +10, 10)
print (np.copysign(np.ceil(np.abs(Z)),Z))

[-3.  4.  3.  9.  8.  1.  3. -1.  3. -9.]


In [107]:
# 30. 如何找到两个数组中的共同元素?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 4]


In [110]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? 
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [111]:
# 32. 下面的表达式是正确的吗? 

np.sqrt(-1) == np.emath.sqrt(-1)

E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False