In [133]:
# 1导入numpy库并简写为 np
import numpy as np

In [135]:
# 2.打印numpy的版本和配置说明
print(np.__version__,np.show_config)

1.15.4 <function show at 0x000001CDDC53A510>


In [29]:
# 3.创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
# 4.如何找到任何一个数组的内存大小？
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [46]:
# 5.如何从命令行得到numpy中add函数的说明文档?
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [31]:
# 6.创建一个长度为10并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
# 7.创建一个值域范围从10到49的向量
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
# 8.反转一个向量(第一个元素变为最后一个)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [34]:
# 9.创建一个 3x3 并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# 10.找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [36]:
# 11.创建一个 3x3 的单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
# 12. 创建一个 3x3x3的随机数组
Z = np.random.random((3,3,3))
print(Z)

[[[0.07550579 0.52581294 0.68802496]
  [0.96634381 0.59929977 0.45221967]
  [0.48063538 0.60627731 0.28663324]]

 [[0.24909215 0.39706963 0.18228038]
  [0.22416956 0.00325136 0.85796467]
  [0.75928213 0.09285065 0.46560094]]

 [[0.28191494 0.04412588 0.44913972]
  [0.2106296  0.54088472 0.90947333]
  [0.87481685 0.80313023 0.31766441]]]


In [38]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 
Z = np.random.random((10,10))
print(Z)
print(Z.max(),Z.min())

[[0.91594083 0.42664164 0.16464361 0.84521999 0.62128921 0.36579389
  0.67197404 0.38807573 0.56528271 0.16594682]
 [0.96367788 0.21930991 0.03823384 0.75016834 0.05454083 0.60381557
  0.76651785 0.69467938 0.53143947 0.33660363]
 [0.46089037 0.6783934  0.94419171 0.20760785 0.26471304 0.67080953
  0.69612618 0.64239647 0.64690949 0.41350905]
 [0.16567988 0.36910476 0.51952003 0.66774108 0.29463307 0.44813574
  0.32811589 0.77479151 0.2672339  0.92281454]
 [0.57293209 0.2188253  0.18211464 0.71715385 0.44229924 0.51672852
  0.62578023 0.28769819 0.95647263 0.55387183]
 [0.3951306  0.44558387 0.24908458 0.36733401 0.36565902 0.28770623
  0.14576306 0.66754296 0.76574144 0.11746592]
 [0.70859471 0.829364   0.75229066 0.22302941 0.98027996 0.92691859
  0.5976727  0.90299428 0.070595   0.4703711 ]
 [0.4901716  0.62831265 0.22224908 0.78191546 0.69324389 0.62876314
  0.66098271 0.69499037 0.29050535 0.94444801]
 [0.49516263 0.04425588 0.78052904 0.46895419 0.07670263 0.16645736
  0.91699719

In [39]:
# 14. 创建一个长度为30的随机向量并找到它的平均值 
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.20725082 0.08361989 0.67253836 0.00971226 0.96599237 0.43722164
 0.57391069 0.69051281 0.07990792 0.16137404 0.46867362 0.46992561
 0.99223798 0.35633413 0.17699172 0.38909015 0.5579309  0.05384233
 0.27262055 0.9436634  0.28658017 0.73170397 0.80113884 0.07379651
 0.81363448 0.2288429  0.71980144 0.48829049 0.12854559 0.45586777]
0.44305177793006406


In [40]:
# 15. 创建一个二维数组，其中边界值为1，其余值为0
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:
# 16. 对于一个存在在数组，如何添加一个用0填充的边界? 
Z = np.ones((5,5))
Z = np.pad(Z,pad_width = 1, mode = 'constant',constant_values = 0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:
# 17. 以下表达式运行的结果分别是什么?
0 * np.nan
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

False
False
nan
False


In [49]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 
Z = np.diag(1 + np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [54]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式 array[beg:end:step]
# 对于多维数组 x[1,2] 表示第1行，第2列
Z = np.zeros((8,8),dtype = int)
Z[1::2, ::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [68]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [69]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
# 22. 对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(),Z.min()
Z = (Z - Zmin)/(Zmax-Zmin)
print(Z)

[[0.73344878 0.40003946 0.48966686 0.7978798  0.50880422]
 [1.         0.64335108 0.82774182 0.22077019 0.51501335]
 [0.33695842 0.21739072 0.86051665 0.09673378 0.46895669]
 [0.11010024 0.70436502 0.77364328 0.27673266 0.        ]
 [0.7157376  0.10792081 0.99613199 0.47162704 0.87182487]]


In [74]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype
color = np.dtype([("r", np.ubyte,1),
                 ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [77]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ 
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [83]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反
Z = np.arange(11)
Z[(3<Z) & (Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [100]:
# 26. 下面脚本运行后的结果是什么?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [98]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个? 
Z = np.arange(5)
Z ** Z

2 << Z >> 2

Z < -Z

1j*Z

Z/1/1

Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [104]:
# 28. 下列表达式的结果分别是什么?
print(np.array(0)/np.array(0))

print(np.array(0) // np.array(0))

np.array([np.nan]).astype(int).astype(float)

nan
0


E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  after removing the cwd from sys.path.


array([-2.14748365e+09])

In [105]:
# 29. 如何从零位对浮点数组做舍入 ?
Z =np.random.uniform(-10, +10, 10)
print (np.copysign(np.ceil(np.abs(Z)),Z))

[-3.  4.  3.  9.  8.  1.  3. -1.  3. -9.]


In [107]:
# 30. 如何找到两个数组中的共同元素?
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 4]


In [110]:
# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? 
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

In [136]:
# 32. 下面的表达式是正确的吗? 

np.sqrt(-1) == np.emath.sqrt(-1)

E:\install\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


False

In [137]:
# 33. 如何得到昨天，今天，明天的日期? datetimes and timedeltas: https://www.jianshu.com/p/336cd77d9914
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
print("Yesterday is " + str(yesterday))
print("Today is " + str(today))
print("Tomorrow is " + str(tomorrow))

Yesterday is 2019-06-23
Today is 2019-06-24
Tomorrow is 2019-06-25


In [138]:
# 34. 如何得到所有与2016年7月对应的日期？
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [139]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [155]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
Z

array([6.89821767, 1.88028547, 9.79619267, 6.72676928, 7.1386025 ,
       7.69975172, 7.65908016, 7.35296039, 1.91114591, 9.38068686])

In [156]:
Z-Z%1

array([6., 1., 9., 6., 7., 7., 7., 7., 1., 9.])

In [157]:
np.floor(Z)

array([6., 1., 9., 6., 7., 7., 7., 7., 1., 9.])

In [158]:
np.ceil(Z)-1

array([6., 1., 9., 6., 7., 7., 7., 7., 1., 9.])

In [159]:
Z.astype(int)

array([6, 1, 9, 6, 7, 7, 7, 7, 1, 9])

In [160]:
np.trunc(Z)

array([6., 1., 9., 6., 7., 7., 7., 7., 1., 9.])

In [162]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
Z = np.tile(np.arange(5),(4,1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [163]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [164]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype = float,count = -1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [167]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [168]:
# 40. 创建一个长度为10的随机向量，并将其排序
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03698544 0.13374404 0.36385504 0.40646696 0.45052343 0.60412127
 0.71124025 0.73092614 0.84020289 0.90613002]


In [171]:
# 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
Z = np.arange(10)
np.add.reduce(Z)

45

In [173]:
# 42. 对于两个随机数组A和B，检查它们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[0 0 1 0 1]
[1 0 0 1 1]
False


In [174]:
# 43. 创建一个只读数组(read-only)
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [175]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.83238944 0.60313698 0.96981604 0.85496596 0.95627803 0.55343594
 0.72733391 0.54566931 0.38090991 0.65423428]
[0.1506124  0.57407752 1.15040731 0.26866873 0.53757778 0.20819231
 1.07409737 0.07999683 0.65924218 0.09045414]


In [176]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.26510172 0.89357698 0.         0.48822425 0.6303589  0.46703323
 0.71711165 0.39979085 0.87229172 0.71499564]


In [178]:
# 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [179]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [180]:
# 48. 打印每个numpy标量类型的最小值和最大值？
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [183]:
# 49. 如何打印一个数组中的所有数值?
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [184]:
# 50. 给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

30


In [186]:
# 51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [187]:
# 52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.46027679 0.10785742 0.01050953 0.69231094 0.5361312
  0.26549109 0.6065839  0.38415999 0.2470779 ]
 [0.46027679 0.         0.52260008 0.45037831 0.35422401 0.13478254
  0.25521893 0.43025035 0.50668243 0.47867197]
 [0.10785742 0.52260008 0.         0.11603863 0.78534002 0.61460673
  0.29123169 0.71131789 0.48982018 0.35086859]
 [0.01050953 0.45037831 0.11603863 0.         0.68190562 0.52569134
  0.25839664 0.59712414 0.37803359 0.24191187]
 [0.69231094 0.35422401 0.78534002 0.68190562 0.         0.21954364
  0.58088484 0.21597882 0.50527683 0.57206956]
 [0.5361312  0.13478254 0.61460673 0.52569134 0.21954364 0.
  0.37466113 0.32353681 0.48015329 0.49075198]
 [0.26549109 0.25521893 0.29123169 0.25839664 0.58088484 0.37466113
  0.         0.58357226 0.50487347 0.41001546]
 [0.6065839  0.43025035 0.71131789 0.59712414 0.21597882 0.32353681
  0.58357226 0.         0.32308112 0.42442927]
 [0.38415999 0.50668243 0.48982018 0.37803359 0.50527683 0.48015329
  0.50487347 0.323081

In [188]:
# Much faster with scipy
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.46027679 0.10785742 0.01050953 0.69231094 0.5361312
  0.26549109 0.6065839  0.38415999 0.2470779 ]
 [0.46027679 0.         0.52260008 0.45037831 0.35422401 0.13478254
  0.25521893 0.43025035 0.50668243 0.47867197]
 [0.10785742 0.52260008 0.         0.11603863 0.78534002 0.61460673
  0.29123169 0.71131789 0.48982018 0.35086859]
 [0.01050953 0.45037831 0.11603863 0.         0.68190562 0.52569134
  0.25839664 0.59712414 0.37803359 0.24191187]
 [0.69231094 0.35422401 0.78534002 0.68190562 0.         0.21954364
  0.58088484 0.21597882 0.50527683 0.57206956]
 [0.5361312  0.13478254 0.61460673 0.52569134 0.21954364 0.
  0.37466113 0.32353681 0.48015329 0.49075198]
 [0.26549109 0.25521893 0.29123169 0.25839664 0.58088484 0.37466113
  0.         0.58357226 0.50487347 0.41001546]
 [0.6065839  0.43025035 0.71131789 0.59712414 0.21597882 0.32353681
  0.58357226 0.         0.32308112 0.42442927]
 [0.38415999 0.50668243 0.48982018 0.37803359 0.50527683 0.48015329
  0.50487347 0.323081

In [189]:
# 53. 如何将32位的浮点数(float)转换为对应的整数(integer)?
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [190]:
# 54. 如何读取以下文件?
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

SyntaxError: invalid syntax (<ipython-input-190-9ea08f0068c3>, line 3)

In [191]:
# 55. 对于numpy数组，enumerate的等价操作是什么？
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
     print (index, value)
for index in np.ndindex(Z.shape):
     print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [192]:
# 56. 生成一个通用的二维Gaussian-like数组
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [193]:
# 57. 对一个二维数组，如何在其内部随机放置p个元素? 
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [194]:
# 58. 减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.21850143  0.25487961  0.18580093  0.34238693  0.35055636 -0.35057476
  -0.44760333 -0.24372272  0.39787979 -0.27110138]
 [-0.25605163 -0.19245271 -0.06519002 -0.19858642 -0.10715615 -0.25950929
   0.34814877  0.28846929  0.52743078 -0.08510262]
 [-0.39084243  0.42974398 -0.27123238 -0.15277555  0.57864379  0.10026274
  -0.03254128 -0.32926017  0.31696729 -0.24896599]
 [-0.02963812  0.26162462 -0.22072453 -0.00481452 -0.00675915  0.36003956
  -0.0710881  -0.2099609   0.19529446 -0.27397333]
 [ 0.25900893 -0.23871346 -0.18516644  0.3608689  -0.37505234 -0.15863133
  -0.36059363  0.07583584  0.07075007  0.55169345]]


In [195]:
# 59. 如何通过第n列对一个数组进行排序?
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[2 9 5]
 [6 2 5]
 [7 0 4]]
[[7 0 4]
 [6 2 5]
 [2 9 5]]


In [196]:
# 60. 如何检查一个二维数组是否有空列？
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


In [197]:
# 61. 从数组中的给定值中找出最近的值 
Z = np.random.uniform(0,1,10)
print(Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

[0.01281836 0.81670372 0.76903594 0.09429959 0.08645815 0.4520244
 0.52806971 0.38765609 0.6169528  0.84598413]
0.5280697133795629


In [198]:
# 62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [199]:
# 63. 创建一个具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [200]:
# 64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? 
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 2. 3. 3. 2. 2. 2. 5. 4. 4.]


In [201]:
#65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [202]:
#66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [203]:
# 67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ 
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[43 56 40 63]
 [42 61 58 56]
 [60 48 53 47]]


In [204]:
# 方法2
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[43 56 40 63]
 [42 61 58 56]
 [60 48 53 47]]
