In [26]:
import numpy as np

In [27]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/install/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/install/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/install/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/instal

In [29]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
np.info(np.add)

800 bytes
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scal

In [31]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [32]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [33]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [34]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [36]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.24534696 0.44432607 0.80616692]
  [0.49125871 0.64576598 0.7594225 ]
  [0.59015901 0.63828106 0.06738928]]

 [[0.06792159 0.65734401 0.61107367]
  [0.64496968 0.75280661 0.19356486]
  [0.9098304  0.43255101 0.98017775]]

 [[0.19565062 0.76077782 0.51590231]
  [0.94255416 0.97595457 0.19776502]
  [0.97545316 0.60710651 0.04570529]]]


In [38]:
Z = np.random.random((10,10))
print(Z)
print(Z.max(),Z.min())

[[0.91594083 0.42664164 0.16464361 0.84521999 0.62128921 0.36579389
  0.67197404 0.38807573 0.56528271 0.16594682]
 [0.96367788 0.21930991 0.03823384 0.75016834 0.05454083 0.60381557
  0.76651785 0.69467938 0.53143947 0.33660363]
 [0.46089037 0.6783934  0.94419171 0.20760785 0.26471304 0.67080953
  0.69612618 0.64239647 0.64690949 0.41350905]
 [0.16567988 0.36910476 0.51952003 0.66774108 0.29463307 0.44813574
  0.32811589 0.77479151 0.2672339  0.92281454]
 [0.57293209 0.2188253  0.18211464 0.71715385 0.44229924 0.51672852
  0.62578023 0.28769819 0.95647263 0.55387183]
 [0.3951306  0.44558387 0.24908458 0.36733401 0.36565902 0.28770623
  0.14576306 0.66754296 0.76574144 0.11746592]
 [0.70859471 0.829364   0.75229066 0.22302941 0.98027996 0.92691859
  0.5976727  0.90299428 0.070595   0.4703711 ]
 [0.4901716  0.62831265 0.22224908 0.78191546 0.69324389 0.62876314
  0.66098271 0.69499037 0.29050535 0.94444801]
 [0.49516263 0.04425588 0.78052904 0.46895419 0.07670263 0.16645736
  0.91699719

In [39]:
Z = np.random.random(30)
print(Z)
print(Z.mean())

[0.20725082 0.08361989 0.67253836 0.00971226 0.96599237 0.43722164
 0.57391069 0.69051281 0.07990792 0.16137404 0.46867362 0.46992561
 0.99223798 0.35633413 0.17699172 0.38909015 0.5579309  0.05384233
 0.27262055 0.9436634  0.28658017 0.73170397 0.80113884 0.07379651
 0.81363448 0.2288429  0.71980144 0.48829049 0.12854559 0.45586777]
0.44305177793006406


In [40]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [42]:

Z = np.ones((5,5))
Z = np.pad(Z,pad_width = 1, mode = 'constant',constant_values = 0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [43]:

0 * np.nan
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


False
False
nan
False


In [44]:

Z = np.diag(1 + np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:

Z = np.zeros((8,8),dtype = int)
Z[1::2, ::2] = 1
Z[::2,1::2] = 1
print(Z)